### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by pascalberger** [McNull/angular-block-ui#104]
It would be nice to have some TypeScript definitions available through DefinitelyTyped for this module.

**Comment by DibranMulder** [comment]
I found out that a company called Monsenso created some [typings ](https://github.com/Monsenso/typings/blob/master/angular-block-ui.d.ts) for it.

**Comment by DibranMulder** [comment]
This issue can be closed since they are added to DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/angular-block-ui
