### ISSUE TITLE
angular-block-ui not working with angular 1.6.0

### ISSUE THREAD

**Issue by dominusbelial** [McNull/angular-block-ui#114]
I'm getting the following on console after updating from angular 1.5.9 to 1.6.0...

angular.js:14324 Possibly unhandled rejection: {} undefined
(anonymous function) @ angular.js:14324
(anonymous function) @ angular.js:10834
(anonymous function) @ angular-block-ui.js:29
g @ angular.js:16668
$eval @ angular.js:17958
$digest @ angular.js:17772
$apply @ angular.js:18066
l @ angular.js:12207
N.onload @ angular.js:12361

**Comment by dominusbelial** [comment]
not an issue its working fine with angular 1.6.0, code was hiding an exception.

**Comment by hbakhtiyor** [comment]
@dominusbelial  the same issue, what do you mean by hiding an exception?

**Comment by dominusbelial** [comment]
@hbakhtiyor error/exception stack was suggesting angular-block-ui but i actually had to upgrade some of my promises to make them fully angular 1.6.x compliant.
