### ISSUE TITLE
problems with angular 1.3.0

### ISSUE THREAD

**Issue by jacqueslareau** [McNull/angular-block-ui#19]
I know 1.3.0 is still beta, but it generates errors ($digest already in progress) and the loading screen doesn't work properly. Tested on v1.3.0-beta.15

**Comment by juboba** [comment]
What up McNull, thanks for providing this. I wonder if angular-block-ui works with angularjs 1.3. I'm trying to use block-ui-pattern="/api\/clients" for url: "http://myserver.com/api/clients" without success.
