### ISSUE TITLE
Append the block-ui element instead of replacing the content

### ISSUE THREAD

**Issue by bsweeney** [McNull/angular-block-ui#29]
I'd like to use this directive by specifying the attribute on the container rather than adding a child element to my markup. I see that I can work around the current implementation by setting transclude to true and adding an element with the ng-transclude attribute to the template.

So instead of this:

```
<div id="my-container">
  <div block-ui="dataload"></div>
  <div id="my-data-table">...</div>
</div>
```

I do something like this:

```
<div id="my-container" block-ui="dataload">
  <div id="my-data-table">...</div>
</div>
```

I've not done any directive development, so I don't know if there are any drawbacks or significant consequences to making this modification.

This is a breaking change from how the block-ui is currently defined and I don't know if you can accommodate both styles (via an option perhaps?). I've managed to get it working, but it does break the blocking element for pages designed for the current implementation.

**Comment by bsweeney** [comment]
It looks like this is maybe done in the latest release?

**Comment by McNull** [comment]
Yup -- markup syntax is now something like:
```
<div block-ui="myBlockUI">
  <p> ... I'm blockable ... </p>
</div>
```
Thanks for the suggestions!
