### ISSUE TITLE
blockUI.stop() is not working

### ISSUE THREAD

**Issue by khanhlu2013** [McNull/angular-block-ui#44]
http://plnkr.co/edit/LRqdjvZY6ISyGeS6TFYK?p=preview

In this plunker, i create 2 local pouchdb instances. insert 200 docs in one db, and replicate it to the other. 

Take a look a the console log:
![screen shot 2014-10-13 at 6 34 33 pm](https://cloud.githubusercontent.com/assets/5914159/4622884/38e0520a-5342-11e4-944a-a7bfa811dee2.png)

after finish replicate, i call blockUI.stop() and you can see the blockUI.state().blocking change from true to false. However, the page is still block

**Comment by stevensmith007** [comment]
When I wrap it in a $scope.$apply(function() {}), I get a $rootScope.inprog error.
If I don't wrap it the the $apply function, the blockUI never stops. Any ideas?

**Comment by necrifede** [comment]
Could you add the link of [plunker ](http://plnkr.co/edit/k4pqQM?p=preview) to documentation please, thus make easy to undertand.

**Comment by necrifede** [comment]
It is rear, using code:
`$scope.$apply(function () { blockUI.stop(); });`
is throwing an error on my site even the stop() funcion is working good:

```
angular.js:12520 Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.4.8/$rootScope/inprog?p0=NaNigest
```

to avoid this error I had to replace it for:
`$scope.$applyAsync(function () { blockUI.stop(); });`

hope this info helps to someone:
I got this info from [here](http://stackoverflow.com/questions/18626039/apply-already-in-progress-error)
