### ISSUE TITLE
Typeahead - Asynchronous results

### ISSUE THREAD

**Issue by vvg-it** [McNull/angular-block-ui#45]
Hi, thank you for your project!
In the http://plnkr.co/edit/GIyC6Xp7qD2DCMKxowdt?p=preview
Static arrays - work,
Asynchronous results - does not work.
How to make it work?

**Comment by McNull** [comment]
Async type-aheads should not be blocked in the user interface and thus be excluded from block-ui.

```
blockUIConfig.requestFilter = function(config) {
    if (config.url.match(/^http:\/\/maps.googleapis.com\/maps\/api\/geocode\/json/)) {
      return false; // ... don't block it.
    }
  };
```
