### ISSUE TITLE
Mouse icon is not reset after unblock happens in Chrome Version 39.0.2171.95 m

### ISSUE THREAD

**Issue by atrishin** [McNull/angular-block-ui#57]
Reproducible at http://angular-block-ui.nullest.com/#!/examples/documentation

Any example will show the issue, as long as mouse pointer is not moved after blocking started, the icon remains to be a spinner until pointer is moved. Chrome Version 39.0.2171.95 m

Works fine in IE/FF.

**Comment by atrishin** [comment]
Moving cursor: wait; from .block-ui-container to .block-ui-active > .block-ui-container seems to help

**Comment by McNull** [comment]
Thanks for the fix!

Implemented in 0.2
