### ISSUE TITLE
blockUIConfig is a  provider instance or a plain simple javascript object in v.0.1.2?

### ISSUE THREAD

**Issue by xiaoxinw** [McNull/angular-block-ui#60]
Hi,I use v.0.1.2 angualr 1.3.8
I want to say it's cool.But there is a issue make me confused
I found this in the doc
"There are two breaking changes for users upgrading from 0.0.x to 0.1.x.
The blockUIConfig is no longer a provider instance but a plain simple javascript object.
The markdown has been simplified."

But when I'm using,the blockUIConfig is sitll a provider since if i don't inject it and use it as a plain simple javascript object, it will get an error say that can't find the "blockUIConfig" provider

**Comment by McNull** [comment]
Can you supply me with an example plunker? Thanks.
