### ISSUE TITLE
Block Ui Minimizes Browser to the Task Bar (Angular 1.3.0)

### ISSUE THREAD

**Issue by markondotnet** [McNull/angular-block-ui#61]
Hi, 

I'm experiencing an issue when I call start() (on block ui) where the browser window disappears and is minimized to the taskbar.  The block call is made from my controller and is simply:

blockUi.start("Doing something.");

I've used block ui before but with version 1.2.x of Angular without issue and am curious if this is a 1.3 issue.

Is this a known issue?  If so, is there a workaround?

Thanks, 
Mark

**Comment by McNull** [comment]
Hi,

that's an odd issue. As far as I know there isn't even a method in javascript to minimize the the browser. Which browser are you using? In Chrome you can start an incognito window to exclude any plugins that might cause this behavior. 

Can you reproduce this in a plunkr, fiddle or a small snippet?

Thanks.

**Comment by markondotnet** [comment]
Hi,

 

Sorry McNull…I’ve been pretty busy.  At some point in the near future, I will put something together and get it to you.

 

The browser versions are IE9 and IE10.

 

Thanks, 

Mark

**Comment by McNull** [comment]
Hi,

Can you try adding the _main block-ui_ element manually instead of letting the module automatically modifying the _body_ element?

In your consuming module:

```
angular.module('myApp').config(function(blockUIConfig) {
  // Tell blockUI not to mark the body element as the main block scope.
  blockUIConfig.autoInjectBodyBlock = false;
});
```

In your _index.html_:

```
<!-- Mark the desired containing element as the main block instance -->
<body>
  <div block-ui="main" class="block-ui-main">
    <!-- ... content ... -->
  </div>
</body>
```

Please let me know if this worked for you.

Thanks.

**Comment by marcosvitali** [comment]
I've debugged that and comment these lines fix:

  //$timeout(function () {
                    //    // Ensure we still need to blur
                    //    if (self._restoreFocus) {
                    //        self._restoreFocus.blur();
                    //    }
                    //});

produce minimize explorer 10 in my case to task bar. I am seeing why you add these lines

**Comment by marcosvitali** [comment]
$timeout(function () {
                        // Ensure we still need to blur
                        if (self._restoreFocus) {
                            self._restoreFocus.blur();
                        }
                    }, 100);

settimeout to 100 also fix the problem in my PC, very strange IE bug

**Comment by marcosvitali** [comment]
http://tjvantoll.com/2013/08/30/bugs-with-document-activeelement-in-internet-explorer/

seems a bugs with explorer and blur

**Comment by marcosvitali** [comment]
well, here the real solution

   $timeout(function () {
                        // Ensure we still need to blur
                        if (self._restoreFocus && self._restoreFocus.nodeName.toLowerCase() !== "body") {
                            self._restoreFocus.blur();
                        }
                    });

the problem is, if the element is body dont need to execute blut.

Enjoy!
