### ISSUE TITLE
displayea only {{state.message}}

### ISSUE THREAD

**Issue by eismue** [McNull/angular-block-ui#63]
Hello,

I assume its just me, but I cannot get it to work to display the message text. The popup ist shown correctly in auto-mode and also after manual blocking calls. But not the message is displayed but {{state.message}}. Therefor the databinding does not performe.

Some infos:
- loading angular-block-ui.css
- loading angular (v1.3.0)
- loading angular-block-ui.min.js ( v0.2.0)
- loading app.js
- creating dependency in app.js (angular.module('myApp', ['kendo.directives', 'ui.bootstrap', 'remoteValidation', 'blockUI']);)

Any hint would be much appreciated. I'm not that skilled in angular & co. and just learning, but angular-blockui is a very usefull tool I'd really like to use.
Thank you, Axel.

**Comment by McNull** [comment]
Hi,

I'm sorry for this late reply -- but do you receive any error messages in the console?

Thanks.

**Comment by eismue** [comment]
No problem at all with delayed response.

In the console there are no (block-ui) error messages. Only one from ui.bootstrap modal but without any remarkable affect.
But after some testing and further investigation and time spending I recognised this error as the rootcause. The bootsrap-ui documentation is obviously misleading on one point and causes this error. The victim was block-ui.
So as assumend its just me (or ui.bootstrap), not block-ui. Thank you and have a nice day. Neat tool!
