### ISSUE TITLE
BlockUI V/s AngularJS 1.3.15 Not working

### ISSUE THREAD

**Issue by sameer22** [McNull/angular-block-ui#71]
I am using BlockUI for the first time. My angular version is 1.3.15.

Today I tried in my project but couldn't see any working from BlockUI. 

Any suggestions. Thanks.

**Comment by tinusn** [comment]
I do not have any problems using it with 1.3.15.

Please provide a sample of whats not working.

**Comment by sameer22** [comment]
I can't see anything blocking during http call.

I followed steps as mentioned on the website
1. Link to CSS
2. Include JS
3. 'blockUI' dependency in app.js

Index.html
<div>
<div ng-view></div>
</div>

Can you suggest any reason what may be I doing wrong

**Comment by sameer22** [comment]
@tinusn Thanks.

You comments encouraged me to see the documentation again & I read it carefully. Things are working fine for me now with Angular 1.3.15
