### ISSUE TITLE
Use GIF image

### ISSUE THREAD

**Issue by NumaanMohd** [McNull/angular-block-ui#90]
Hello,

How to use GIF image in angular-block-ui??

**Comment by roymj88** [comment]
:+1:  This would be a very good feature if possible.

**Comment by iwannabaa** [comment]
@NumaanMohd You can add you own template that includes a GIF image using `blockUIConfig.templateUrl`. I did it by using this:

``` html
<div class="block-ui-container">
  <div class="block-ui-overlay"></div>
  <div class="block-ui-message-container">
    <div class="block-ui-message">
      <img src="images/spinner.gif">
    </div>
  </div>
</div>
```

I kept original classes and layout so it display the same overlay and box styles.

**Comment by NumaanMohd** [comment]
Thanks @iwannabaa. Sorry for the late response.
