### ISSUE TITLE
Correct Angular version dependency? ~1.2.4

### ISSUE THREAD

**Issue by junketjim** [McNull/angular-block-ui#94]
Angular has moved on a lot since 1.2.4 and I was wondering if the dependency of ~1.2.4 was still valid?
Would a dependency of ~1 be more appropriate?  Otherwise, I believe we're pinned to < 1.3.x

I fully appreciate that 0.2.0 of block-ui may have only been tested against Angular 1.2.x - but this is now legacy and the latest stable is 1.4.x

For reference, the semver notation that bower uses - https://github.com/npm/node-semver#tilde-ranges-123-12-1

**Comment by McNull** [comment]
I've modified the dependencies to version ~1.

Thanks.
