### ISSUE TITLE
Change block-ui default location

### ISSUE THREAD

**Issue by erickne** [McNull/angular-block-ui#95]
I tried to set in na specific div but it keeps showing in full screen. How can I use block-ui for all request (as default) but show only in `<div class="content"></div>`?

**Comment by McNull** [comment]
Hi,

You can relocate the _main_ blockUI instance by setting [autoInjectBodyBlock](https://github.com/McNull/angular-block-ui/tree/v0.2.2#autoinjectbodyblock) to `false` in the configuration and marking your custom element with `block-ui="main"`.

See this [plunker](http://plnkr.co/edit/X4dTgE?p=preview) for more info.
